---
apiVersion: v1
kind: Service
metadata:
  name: demo-kubernetes
  labels:
    app: demo-kubernetes
spec:
  type: LoadBalancer
  selector:
    app: demo-kubernetes
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-kubernetes
spec:
  selector:
    matchLabels:
      app: demo-kubernetes
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-kubernetes
    spec:
      containers:
        - name: demo-kubernetes
          image: bhoopendra/demo-kubernetes:configMapTest7
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CLOUD_BOOTSTRAP_ENABLED
              value: "true"
            - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLEAPI
              value: "true"
          livenessProbe:
            httpGet:
              path: /demokubernetes/actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 1