kind: ConfigMap
apiVersion: v1
metadata:
  name: roboapp-app-config
data:
  application.yml: |-
    greeting:
      message: Say Hello to the World
    farewell:
      message: Say Goodbye
    smartrobo:
      version: 11.0.2